
import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisResult, GroundingSource } from '../types';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const responseSchema = {
  type: Type.OBJECT,
  properties: {
    factuality: {
      type: Type.OBJECT,
      properties: {
        score: {
          type: Type.INTEGER,
          description: "A fact confidence score from 0 to 100, where 100 is completely factual.",
        },
        explanation: {
          type: Type.STRING,
          description: "A short explanation of the factuality score, mentioning sources if found.",
        },
      },
      required: ["score", "explanation"],
    },
    bias: {
      type: Type.OBJECT,
      properties: {
        score: {
          type: Type.NUMBER,
          description: "A score from -1.0 (strongly negative bias) to +1.0 (strongly positive bias), with 0 being neutral.",
        },
        summary: {
          type: Type.STRING,
          description: "A qualitative summary of the detected bias.",
        },
      },
      required: ["score", "summary"],
    },
    authorship: {
      type: Type.OBJECT,
      properties: {
        classification: {
          type: Type.STRING,
          enum: ["Likely AI-generated", "Likely human-written", "Unclear"],
          description: "The likelihood of the text being AI-generated.",
        },
      },
      required: ["classification"],
    },
    summary: {
      type: Type.OBJECT,
      properties: {
        text: {
          type: Type.STRING,
          description: "A short, semantic summary of the input text.",
        },
        topics: {
          type: Type.ARRAY,
          items: {
            type: Type.STRING,
          },
          description: "A list of the main topics or keywords discussed in the text.",
        },
        sentiment: {
            type: Type.NUMBER,
            description: "A score from -1.0 (very negative sentiment) to +1.0 (very positive sentiment)."
        }
      },
      required: ["text", "topics", "sentiment"],
    },
  },
  required: ["factuality", "bias", "authorship", "summary"],
};


export const analyzeTextWithGemini = async (text: string): Promise<AnalysisResult> => {
  const systemInstruction = `You are TruthLens, a sophisticated AI text analyzer. Your purpose is to perform a deep semantic and factual verification of the user's text. You must use the provided googleSearch tool to cross-reference claims and provide a factual analysis. Provide your analysis in the required JSON format.
  - Fact Verification: Detect factual claims and cross-check them using real-time search results. Provide a 'Fact Confidence Score' (0-100) and an explanation.
  - Bias Detection: Identify subjective or emotionally charged language. Classify text bias on a scale from -1 (strongly negative) to +1 (strongly positive) and provide a qualitative summary.
  - AI Authorship Detection: Analyze stylometric properties to determine if the text was likely generated by an AI.
  - Semantic Summary: Generate a concise summary, extract main topics, and determine the overall sentiment.`;

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: {
      role: 'user',
      parts: [{ text: text }],
    },
    config: {
      systemInstruction,
      responseMimeType: "application/json",
      responseSchema: responseSchema,
      tools: [{ googleSearch: {} }],
    },
  });
  
  const jsonText = response.text.trim();
  const parsedResult = JSON.parse(jsonText);

  const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
  const sources: GroundingSource[] = groundingChunks
    .map(chunk => chunk.web)
    .filter(web => web?.uri && web.title)
    .map(web => ({ uri: web.uri, title: web.title }))
    // Deduplicate sources based on URI
    .filter((source, index, self) => 
        index === self.findIndex((s) => s.uri === source.uri)
    );

  return { ...parsedResult, sources };
};
